<<<<<<< HEAD
# Generated by Django 3.2.6 on 2022-06-14 04:29
=======
# Generated by Django 3.2.5 on 2022-06-08 05:30
>>>>>>> 61e4d3f985c9c8ac868ca25a1de9e0b31bb93907

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
<<<<<<< HEAD
            field=models.CharField(choices=[('is_staff', 'is_staff'), ('is_student', 'is_student'), ('is_admin', 'is_admin')], default='0', max_length=20),
=======
            field=models.CharField(choices=[('is_student', 'is_student'), ('is_admin', 'is_admin'), ('is_staff', 'is_staff')], default='0', max_length=20),
>>>>>>> 61e4d3f985c9c8ac868ca25a1de9e0b31bb93907
        ),
    ]
