# Generated by Django 3.2.5 on 2022-08-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_instruction_instruction_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionForTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
