# Generated by Django 3.2.5 on 2022-08-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_instructionfortest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionfortest',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
