# Generated by Django 3.2.5 on 2022-08-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_instructionfortest_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.AlterField(
            model_name='instructionfortest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
