# Generated by Django 3.2.5 on 2022-08-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_auto_20220809_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_paper',
            name='test_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
