# Generated by Django 3.2.13 on 2022-09-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_question_chapter_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='question_files/')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='answer_files/')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
            ],
        ),
    ]
