# Generated by Django 3.2.13 on 2022-09-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_auto_20220926_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='test_details',
            new_name='test_detail',
        ),
    ]
