# Generated by Django 3.2.13 on 2022-09-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_rename_test_detail_testresult_test_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='test_details',
            new_name='test_detail',
        ),
    ]
