# Generated by Django 3.2.5 on 2022-08-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='instruction',
            new_name='instruction_text',
        ),
    ]
