# Generated by Django 3.2.13 on 2022-09-26 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='testdetails',
        ),
    ]
