# Generated by Django 3.2.5 on 2022-08-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='correct_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='wrong_answer',
            field=models.IntegerField(null=True),
        ),
    ]
