# Generated by Django 3.2.5 on 2022-08-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20220805_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='unanswered_questions',
            field=models.IntegerField(null=True),
        ),
    ]
