# Generated by Django 3.2.5 on 2022-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_instruction_instruction_instruction_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text',
            field=models.CharField(max_length=60),
        ),
    ]
