# Generated by Django 3.2.5 on 2022-08-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_question_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('subject', 'chapter_no')},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ('grade',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('grade', 'subject', 'chapter', 'question_type', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='question_paper',
            options={'ordering': ('grade', 'subject', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('grade', 'name')},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('grade', 'subject', 'created_staff_id', 'question_paper')},
        ),
        migrations.AddField(
            model_name='question',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject'),
        ),
    ]
