# Generated by Django 3.2.5 on 2022-08-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20220808_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
