# Generated by Django 3.2.5 on 2022-08-08 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_instruct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 16, 42, 56, 899649)),
        ),
    ]
