# Generated by Django 3.2.6 on 2022-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_auto_20220614_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Comprehension', 'Comprehension'), ('Application', 'Application'), ('Knowledge', 'Knowledge')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Easy', 'Easy'), ('Hard', 'Hard')], default='0', max_length=20),
        ),
    ]
