# Generated by Django 3.2.5 on 2022-08-08 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 16, 47, 4, 753688)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 16, 47, 4, 753968)),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 16, 47, 4, 754637)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 16, 47, 4, 753414)),
        ),
    ]
