# Generated by Django 3.2.5 on 2022-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_question_paper_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=35),
        ),
    ]
