# Generated by Django 3.2.13 on 2022-08-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_test_pass_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('grade', 'code', 'name')},
        ),
    ]
