# Generated by Django 3.2.13 on 2022-08-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_subject_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_paper',
            name='overall_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question_paper',
            name='timing',
            field=models.IntegerField(default=0),
        ),
    ]
