# Generated by Django 3.2.13 on 2022-08-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_auto_20220823_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter_no',
            field=models.IntegerField(default=0),
        ),
    ]
