# Generated by Django 3.2.13 on 2022-09-23 07:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_questionbank_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='testdetails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, default=list, size=None),
        ),
    ]
