# Generated by Django 3.2.13 on 2022-09-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_testresult_testdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='testdetails',
        ),
    ]
