# Generated by Django 3.2.13 on 2022-09-23 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_testresult_testdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='testdetails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
    ]
